//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生（Visual Studio Web Forms 設計工具）。
//
//     變更此檔案可能導致不正確的行為；重新產生程式碼時，變更將會遺失。
//     新增或移除 .aspx 中的 runat="server" 控制項時，需同步更新此檔。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{


    /// <summary>
    /// 結帳頁（checkout.aspx）的設計工具產生部分：宣告頁面上所有 runat="server" 控制項欄位。
    /// </summary>
    public partial class checkout
    {

        /// <summary>
        /// 伺服器端表單「form1」：頁面唯一的伺服器端表單，包住所有伺服器控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// 超連結「Logo」：頁首 Logo 連結，點選回到 index.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Logo;

        /// <summary>
        /// 選單「HeaderMenu」：頁首主選單：Home、Shop（Categories / Cart）、About、Blog、Contact。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu HeaderMenu;

        /// <summary>
        /// 選單「Menu1」：頁首帳號選單：Sign In、Register（User / Seller）；登入後於 Page_Load 隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu Menu1;

        /// <summary>
        /// 按鈕「btnLogout」：登出按鈕：預設隱藏，登入後顯示；點選時清除 Session["user"] 並導回首頁。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// 圖片按鈕「searchIcon」：頁首搜尋圖示（本頁未綁定點選事件，僅首頁提供搜尋）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton searchIcon;

        /// <summary>
        /// 圖片按鈕「profileIcon」：頁首個人資料圖示：預設隱藏，登入後顯示並導向 profile.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton profileIcon;

        /// <summary>
        /// 圖片按鈕「cartIcon」：頁首購物車圖示：預設隱藏，登入後顯示並導向 cart.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton cartIcon;

        /// <summary>
        /// 標籤「countItems」：購物車徽章：顯示 Session["count"]（購物車 DataTable）的品項數，登入後顯示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label countItems;

        /// <summary>
        /// 圖片「FreeShipping」：頁尾「Free Shipping」促銷圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image FreeShipping;

        /// <summary>
        /// 標籤「FreeShippingDetail」：頁尾免運說明文字（Free Shipping on orders over Rs.150* in India）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FreeShippingDetail;

        /// <summary>
        /// 圖片「Voucher」：頁尾「Voucher」優惠券圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Voucher;

        /// <summary>
        /// 標籤「VoucherDetail」：頁尾優惠券說明文字（20% Student Discount）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VoucherDetail;

        /// <summary>
        /// 圖片「Discount」：頁尾「Discount」折扣圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Discount;

        /// <summary>
        /// 標籤「DiscountDetail」：頁尾折扣說明文字（30% off on dresses. Use code: 30OFF）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DiscountDetail;

        /// <summary>
        /// 標籤「lblCheckouttMsg」：頁面標題「Checkout」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCheckouttMsg;

        /// <summary>
        /// 面板「Panel1」：訂單確認面板：顯示訂單編號、日期與明細。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel1;

        /// <summary>
        /// 標籤「Label1」：「Order ID」標題文字。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// 標籤「orderID」：本次訂單編號（由後置程式碼產生）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label orderID;

        /// <summary>
        /// 標籤「Label2」：「Order Date」標題文字。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;

        /// <summary>
        /// 標籤「orderDate」：本次訂單日期。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label orderDate;

        /// <summary>
        /// 表格「GridView1」：訂單明細表格：繫結 Session["count"] 的購物車內容。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// 按鈕「btnCheckout」：「Place Order」按鈕：寫入 violet_order 並清空 violet_cart。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCheckout;

        /// <summary>
        /// 面板「completeOrder」：下單完成面板：成功下單後顯示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel completeOrder;

        /// <summary>
        /// 標籤「Label7」：「Order Placed Succcessfully」成功訊息。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label7;

        /// <summary>
        /// 標籤「Label3」：完成面板「Order ID」標題文字。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;

        /// <summary>
        /// 標籤「orderIDCompleted」：完成面板：已成立的訂單編號。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label orderIDCompleted;

        /// <summary>
        /// 標籤「Label5」：完成面板「Order Date」標題文字。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label5;

        /// <summary>
        /// 標籤「orderDateCompleted」：完成面板：已成立訂單的日期。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label orderDateCompleted;
    }
}
