//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生（Visual Studio Web Forms 設計工具）。
//
//     變更此檔案可能導致不正確的行為；重新產生程式碼時，變更將會遺失。
//     新增或移除 .aspx 中的 runat="server" 控制項時，需同步更新此檔。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{


    /// <summary>
    /// 錯誤頁（error.aspx）的設計工具產生部分：本頁刻意不使用 runat="server" 控制項，因此沒有控制項欄位。
    /// </summary>
    public partial class error
    {
    }
}
