//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生（Visual Studio Web Forms 設計工具）。
//
//     變更此檔案可能導致不正確的行為；重新產生程式碼時，變更將會遺失。
//     新增或移除 .aspx 中的 runat="server" 控制項時，需同步更新此檔。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{


    /// <summary>
    /// 忘記密碼頁（forgotpass.aspx）的設計工具產生部分：宣告頁面上所有 runat="server" 控制項欄位。
    /// </summary>
    public partial class forgotpass
    {

        /// <summary>
        /// 伺服器端表單「form1」：頁面唯一的伺服器端表單，包住所有伺服器控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// 超連結「Logo」：頁首 Logo 連結，點選回到 index.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Logo;

        /// <summary>
        /// 選單「HeaderMenu」：頁首主選單：Home、Shop（Categories / Cart）、About、Blog、Contact。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu HeaderMenu;

        /// <summary>
        /// 選單「Menu1」：頁首帳號選單：Sign In、Register（User / Seller）；登入後於 Page_Load 隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu Menu1;

        /// <summary>
        /// 按鈕「btnLogout」：登出按鈕：預設隱藏，登入後顯示；點選時清除 Session["user"] 並導回首頁。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// 圖片按鈕「searchIcon」：頁首搜尋圖示（本頁未綁定點選事件，僅首頁提供搜尋）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton searchIcon;

        /// <summary>
        /// 圖片按鈕「profileIcon」：頁首個人資料圖示：預設隱藏，登入後顯示並導向 profile.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton profileIcon;

        /// <summary>
        /// 圖片按鈕「cartIcon」：頁首購物車圖示：預設隱藏，登入後顯示並導向 cart.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton cartIcon;

        /// <summary>
        /// 標籤「countItems」：購物車徽章：顯示 Session["count"]（購物車 DataTable）的品項數，登入後顯示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label countItems;

        /// <summary>
        /// 圖片「FreeShipping」：頁尾「Free Shipping」促銷圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image FreeShipping;

        /// <summary>
        /// 標籤「FreeShippingDetail」：頁尾免運說明文字（Free Shipping on orders over Rs.150* in India）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FreeShippingDetail;

        /// <summary>
        /// 圖片「Voucher」：頁尾「Voucher」優惠券圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Voucher;

        /// <summary>
        /// 標籤「VoucherDetail」：頁尾優惠券說明文字（20% Student Discount）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VoucherDetail;

        /// <summary>
        /// 圖片「Discount」：頁尾「Discount」折扣圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Discount;

        /// <summary>
        /// 標籤「DiscountDetail」：頁尾折扣說明文字（30% off on dresses. Use code: 30OFF）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DiscountDetail;

        /// <summary>
        /// 標籤「lblLoginMsg」：頁面標題「Password Recovery」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLoginMsg;

        /// <summary>
        /// 面板「usernamePanel」：步驟一面板：輸入使用者名稱或 Email。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel usernamePanel;

        /// <summary>
        /// 文字方塊「txtUsername」：使用者名稱輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// 必填驗證器「validateUsernameEmpty」：使用者名稱（txtUsername）必填驗證，錯誤訊息：「Username cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateUsernameEmpty;

        /// <summary>
        /// 標籤「lblErrorMsg」：查無帳號時顯示的錯誤訊息。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorMsg;

        /// <summary>
        /// 按鈕「submit」：步驟一送出按鈕：查詢帳號並載入安全問題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button submit;

        /// <summary>
        /// 面板「passwordPanel」：步驟二面板：回答安全問題，預設隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel passwordPanel;

        /// <summary>
        /// 標籤「lblSec」：顯示該帳號的安全問題（secq）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSec;

        /// <summary>
        /// 文字方塊「txtSecA」：安全問題答案輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSecA;

        /// <summary>
        /// 標籤「lblError」：安全問題答錯時顯示的錯誤訊息。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// 按鈕「submitAns」：步驟二送出按鈕：比對答案，正確則以 Email 寄出密碼。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button submitAns;

        /// <summary>
        /// 標籤「lblSuccess」：密碼已寄出的成功訊息，預設隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSuccess;
    }
}
