//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生（Visual Studio Web Forms 設計工具）。
//
//     變更此檔案可能導致不正確的行為；重新產生程式碼時，變更將會遺失。
//     新增或移除 .aspx 中的 runat="server" 控制項時，需同步更新此檔。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{


    /// <summary>
    /// 賣家註冊頁（sellerRegister.aspx）的設計工具產生部分：宣告頁面上所有 runat="server" 控制項欄位。
    /// </summary>
    public partial class sellerRegister
    {

        /// <summary>
        /// 伺服器端表單「form1」：頁面唯一的伺服器端表單，包住所有伺服器控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// 超連結「Logo」：頁首 Logo 連結，點選回到 index.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Logo;

        /// <summary>
        /// 選單「HeaderMenu」：頁首主選單：Home、Shop（Categories / Cart）、About、Blog、Contact。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu HeaderMenu;

        /// <summary>
        /// 選單「Menu1」：頁首帳號選單：Sign In、Register（User / Seller）；登入後於 Page_Load 隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu Menu1;

        /// <summary>
        /// 按鈕「btnLogout」：登出按鈕：預設隱藏，登入後顯示；點選時清除 Session["user"] 並導回首頁。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// 圖片按鈕「searchIcon」：頁首搜尋圖示（本頁未綁定點選事件，僅首頁提供搜尋）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton searchIcon;

        /// <summary>
        /// 圖片按鈕「profileIcon」：頁首個人資料圖示：預設隱藏，登入後顯示並導向 profile.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton profileIcon;

        /// <summary>
        /// 圖片按鈕「cartIcon」：頁首購物車圖示：預設隱藏，登入後顯示並導向 cart.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton cartIcon;

        /// <summary>
        /// 標籤「countItems」：購物車徽章：顯示 Session["count"]（購物車 DataTable）的品項數，登入後顯示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label countItems;

        /// <summary>
        /// 圖片「FreeShipping」：頁尾「Free Shipping」促銷圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image FreeShipping;

        /// <summary>
        /// 標籤「FreeShippingDetail」：頁尾免運說明文字（Free Shipping on orders over Rs.150* in India）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FreeShippingDetail;

        /// <summary>
        /// 圖片「Voucher」：頁尾「Voucher」優惠券圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Voucher;

        /// <summary>
        /// 標籤「VoucherDetail」：頁尾優惠券說明文字（20% Student Discount）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VoucherDetail;

        /// <summary>
        /// 圖片「Discount」：頁尾「Discount」折扣圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Discount;

        /// <summary>
        /// 標籤「DiscountDetail」：頁尾折扣說明文字（30% off on dresses. Use code: 30OFF）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DiscountDetail;

        /// <summary>
        /// 標籤「lblSignupMsg」：頁面標題「Seller Registration Page」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSignupMsg;

        /// <summary>
        /// 標籤「lblImportant」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblImportant;

        /// <summary>
        /// 文字方塊「txtName」：姓名輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// 必填驗證器「validateNameEmpty」：姓名（txtName）必填驗證，錯誤訊息：「Name field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateNameEmpty;

        /// <summary>
        /// 正規表示式驗證器「validateName」：姓名（txtName）格式驗證，錯誤訊息：「Name should not contain any Numbers or Special Characters」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validateName;

        /// <summary>
        /// 標籤「Label1」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// 文字方塊「txtEmail」：Email 輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// 必填驗證器「validateEmailEmpty」：Email（txtEmail）必填驗證，錯誤訊息：「Email-ID field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateEmailEmpty;

        /// <summary>
        /// 正規表示式驗證器「validateEmail」：Email（txtEmail）格式驗證，錯誤訊息：「Incorrect Email-ID」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validateEmail;

        /// <summary>
        /// 標籤「Label2」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;

        /// <summary>
        /// 文字方塊「txtUsername」：使用者名稱輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// 必填驗證器「validateUsernameEmpty」：使用者名稱（txtUsername）必填驗證，錯誤訊息：「Username field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateUsernameEmpty;

        /// <summary>
        /// 標籤「Label3」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;

        /// <summary>
        /// 文字方塊「txtPassword」：密碼輸入框（TextMode=Password）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// 必填驗證器「validatePasswordEmpty」：密碼（txtPassword）必填驗證，錯誤訊息：「Password field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validatePasswordEmpty;

        /// <summary>
        /// 正規表示式驗證器「validatePasswordExp」：密碼強度驗證：至少 8 碼，需含大小寫字母、數字與特殊字元（@$!%*?&）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validatePasswordExp;

        /// <summary>
        /// 標籤「Label4」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label4;

        /// <summary>
        /// 文字方塊「txtConfirmPassword」：確認密碼輸入框（TextMode=Password）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// 必填驗證器「validateConfirmEmpty」：確認密碼（txtConfirmPassword）必填驗證，錯誤訊息：「Confirm Password field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateConfirmEmpty;

        /// <summary>
        /// 比較驗證器「validateConfirm」：確認密碼比對驗證：txtConfirmPassword 必須與 txtPassword 相同。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompareValidator validateConfirm;

        /// <summary>
        /// 標籤「Label5」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label5;

        /// <summary>
        /// 文字方塊「txtPhone」：電話號碼輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// 必填驗證器「validatePhoneEmpty」：電話（txtPhone）必填驗證，錯誤訊息：「Enter Phone Number」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validatePhoneEmpty;

        /// <summary>
        /// 正規表示式驗證器「validatePhone」：電話（txtPhone）格式驗證，錯誤訊息：「Phone number can only contain numbers」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validatePhone;

        /// <summary>
        /// 標籤「Label6」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label6;

        /// <summary>
        /// 文字方塊「txtDOB」：出生日期輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDOB;

        /// <summary>
        /// 比較驗證器「validateAge」：出生日期驗證（CompareValidator）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompareValidator validateAge;

        /// <summary>
        /// 標籤「Label7」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label7;

        /// <summary>
        /// 下拉選單「selectCountry」：國家下拉選單；變更時連動載入 selectState。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectCountry;

        /// <summary>
        /// 標籤「Label8」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label8;

        /// <summary>
        /// 下拉選單「selectState」：州／省下拉選單；變更時連動載入 selectCity。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectState;

        /// <summary>
        /// 標籤「Label9」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label9;

        /// <summary>
        /// 下拉選單「selectCity」：城市下拉選單。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectCity;

        /// <summary>
        /// 單選按鈕清單「selectGender」：性別單選按鈕清單。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList selectGender;

        /// <summary>
        /// 標籤「Label13」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label13;

        /// <summary>
        /// 多行文字區塊「txtAddress」：完整地址輸入框（多行）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea txtAddress;

        /// <summary>
        /// 必填驗證器「validateAddress」：地址（txtAddress）必填驗證，錯誤訊息：「Address Field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateAddress;

        /// <summary>
        /// 標籤「Label11」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label11;

        /// <summary>
        /// 下拉選單「txtSecurityQ」：安全問題下拉選單（忘記密碼時使用）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList txtSecurityQ;

        /// <summary>
        /// 標籤「Label12」：必填欄位的紅色星號標示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label12;

        /// <summary>
        /// 文字方塊「txtSecurityA」：安全問題答案輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSecurityA;

        /// <summary>
        /// 必填驗證器「RequiredFieldValidator1」：安全問題答案（txtSecurityA）必填驗證，錯誤訊息：「Answer field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        /// <summary>
        /// 按鈕「Submit」：註冊按鈕：寫入 violet_user_login（僅 13 欄，未含 uid）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Submit;

        /// <summary>
        /// 標籤「Label10」：頁尾說明「* - All fields are to be filled.」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label10;
    }
}
