//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生（Visual Studio Web Forms 設計工具）。
//
//     變更此檔案可能導致不正確的行為；重新產生程式碼時，變更將會遺失。
//     新增或移除 .aspx 中的 runat="server" 控制項時，需同步更新此檔。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{


    /// <summary>
    /// 賣家個人資料頁（sellerProfile.aspx）的設計工具產生部分：宣告頁面上所有 runat="server" 控制項欄位。
    /// </summary>
    public partial class sellerProfile
    {

        /// <summary>
        /// 伺服器端表單「form1」：頁面唯一的伺服器端表單，包住所有伺服器控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// 超連結「Logo」：頁首 Logo 連結，點選回到 index.aspx。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Logo;

        /// <summary>
        /// 選單「HeaderMenu」：頁首主選單：Home、Shop（Categories、Product Page、Cart；此頁三者未設定 NavigateUrl）、About、Blog、Contact。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu HeaderMenu;

        /// <summary>
        /// 選單「Menu1」：頁首帳號選單：Sign In、Register（User / Seller）；登入後於 Page_Load 隱藏。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu Menu1;

        /// <summary>
        /// 按鈕「btnLogout」：登出按鈕：預設隱藏，登入後顯示；點選時清除 Session["user"] 並導回首頁。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// 圖片「FreeShipping」：頁首資訊列「Free Shipping」促銷圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image FreeShipping;

        /// <summary>
        /// 標籤「FreeShippingDetail」：頁首資訊列免運說明文字（Free Shipping on orders over Rs.150* in India）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FreeShippingDetail;

        /// <summary>
        /// 圖片「Voucher」：頁首資訊列「Voucher」優惠券圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Voucher;

        /// <summary>
        /// 標籤「VoucherDetail」：頁首資訊列優惠券說明文字（20% Student Discount）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VoucherDetail;

        /// <summary>
        /// 圖片「Discount」：頁首資訊列「Discount」折扣圖示。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Discount;

        /// <summary>
        /// 標籤「DiscountDetail」：頁首資訊列折扣說明文字（30% off on dresses. Use code: 30OFF）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DiscountDetail;

        /// <summary>
        /// 標籤「lblSignupMsg」：區塊標題「Personal Details」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSignupMsg;

        /// <summary>
        /// 標籤「lblName」：「Name :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblName;

        /// <summary>
        /// 文字方塊「txtName」：姓名輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// 必填驗證器「validateNameEmpty」：姓名（txtName）必填驗證，錯誤訊息：「Name field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateNameEmpty;

        /// <summary>
        /// 正規表示式驗證器「validateName」：姓名（txtName）格式驗證，錯誤訊息：「Name should not contain any Numbers or Special Characters」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validateName;

        /// <summary>
        /// 標籤「lblEmail」：「Email :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// 文字方塊「txtEmail」：Email 輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// 必填驗證器「validateEmailEmpty」：Email（txtEmail）必填驗證，錯誤訊息：「Email-ID field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateEmailEmpty;

        /// <summary>
        /// 正規表示式驗證器「validateEmail」：Email（txtEmail）格式驗證，錯誤訊息：「Incorrect Email-ID」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validateEmail;

        /// <summary>
        /// 標籤「lblUsername」：「Username :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// 文字方塊「txtUsername」：使用者名稱輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// 必填驗證器「validateUsernameEmpty」：使用者名稱（txtUsername）必填驗證，錯誤訊息：「Username field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateUsernameEmpty;

        /// <summary>
        /// 標籤「lblPhone」：「Phone :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPhone;

        /// <summary>
        /// 文字方塊「txtPhone」：電話號碼輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// 必填驗證器「validatePhoneEmpty」：電話（txtPhone）必填驗證，錯誤訊息：「Enter Phone Number」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validatePhoneEmpty;

        /// <summary>
        /// 正規表示式驗證器「validatePhone」：電話（txtPhone）格式驗證，錯誤訊息：「Phone number can only contain numbers」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator validatePhone;

        /// <summary>
        /// 標籤「lblDOB」：「DOB :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDOB;

        /// <summary>
        /// 文字方塊「txtDOB」：出生日期輸入框。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDOB;

        /// <summary>
        /// 比較驗證器「validateAge」：出生日期驗證（CompareValidator）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompareValidator validateAge;

        /// <summary>
        /// 標籤「lblGender1」：「Gender :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblGender1;

        /// <summary>
        /// 標籤「lblGender」：顯示使用者性別（唯讀）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblGender;

        /// <summary>
        /// 標籤「lblAddress」：「Address :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAddress;

        /// <summary>
        /// 多行文字區塊「txtAddress」：完整地址輸入框（多行）。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea txtAddress;

        /// <summary>
        /// 必填驗證器「validateAddress」：地址（txtAddress）必填驗證，錯誤訊息：「Address Field cannot be left blank」。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator validateAddress;

        /// <summary>
        /// 標籤「lblCountry1」：「Country :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCountry1;

        /// <summary>
        /// 下拉選單「selectCountry」：國家下拉選單；選項固定寫在 .aspx 標記中，沒有連動載入。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectCountry;

        /// <summary>
        /// 標籤「lblState1」：「State :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblState1;

        /// <summary>
        /// 下拉選單「selectState」：州／省下拉選單；選項固定寫在 .aspx 標記中，沒有連動載入。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectState;

        /// <summary>
        /// 標籤「lblCity1」：「City :」欄位標題。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCity1;

        /// <summary>
        /// 下拉選單「selectCity」：城市下拉選單。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList selectCity;

        /// <summary>
        /// 按鈕「Update」：「Update」按鈕：切換為可編輯模式。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Update;

        /// <summary>
        /// 按鈕「Submit」：「Submit」按鈕：更新功能尚未實作。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從 designer 檔移至後置程式碼檔。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Submit;
    }
}
